import type{BillingService}from"../billing/service.ts";import{createHash}from"node:crypto";import{readFileSync}from"node:fs";import{createServer,type IncomingMessage,type ServerResponse}from"node:http";import{exportResultsCsv,parseEmailCsv}from"../bulk/csv.ts";import type{BulkRepository}from"../bulk/model.ts";import type{BulkService}from"../bulk/service.ts";import type{Clock}from"../domain/clock.ts";import type{VerificationRequest}from"../domain/model.ts";import type{VerificationRepository}from"../domain/repositories.ts";import type{ApiRateLimiter}from"../infrastructure/api-rate-limiter.ts";import type{InMemoryMetrics}from"../infrastructure/metrics.ts";import type{Principal,ProductStore,Scope}from"../product/store.ts";import{createVerificationRequest,type VerificationOrchestrator}from"../verification/orchestrator.ts";
export interface ApiDependencies{readonly billing?:BillingService;readonly orchestrator:VerificationOrchestrator;readonly repository:VerificationRepository;readonly clock:Clock;readonly bulk?:BulkService;readonly bulkRepository?:BulkRepository;readonly rateLimiter?:ApiRateLimiter;readonly metrics?:InMemoryMetrics;readonly product?:ProductStore;authenticate(token:string):Principal|{tenantId:string}|undefined;}
const send=(r:ServerResponse,status:number,value:unknown):void=>{const p=JSON.stringify(value);r.writeHead(status,{"content-type":"application/json","content-length":Buffer.byteLength(p)});r.end(p);};
const rawBody=async(r:IncomingMessage,limit=10_000_000):Promise<Buffer>=>{let size=0;const chunks:Buffer[]=[];for await(const chunk of r){const value=Buffer.from(chunk);size+=value.length;if(size>limit)throw Object.assign(new Error("payload too large"),{status:413});chunks.push(value);}return Buffer.concat(chunks);};
const body=async(r:IncomingMessage):Promise<Record<string,unknown>>=>{try{return JSON.parse((await rawBody(r,65_536)).toString("utf8"));}catch{throw Object.assign(new Error("invalid JSON"),{status:400});}};
const scoped=(p:Principal|{tenantId:string},scope:Scope):boolean=>!("scopes"in p)||p.scopes.has(scope);
const quota=(d:ApiDependencies,p:Principal|{tenantId:string},kind:string,reference:string,quantity:number)=>d.product&&"monthlyQuota"in p?d.product.consume(p,kind,reference,quantity):{allowed:true,used:0,limit:0};
export const createApiServer=(d:ApiDependencies)=>createServer(async(request,response)=>{try{
 if(request.url==="/health"&&request.method==="GET")return send(response,200,{status:"ok",release:"controlled_beta"});
 if(request.url==="/openapi.yaml"&&request.method==="GET"){const v=readFileSync(new URL("../../openapi.yaml",import.meta.url));response.writeHead(200,{"content-type":"application/yaml","content-length":v.length});return response.end(v);}
 if(request.url==="/dashboard"&&request.method==="GET"){const v=readFileSync(new URL("../../public/dashboard.html",import.meta.url));response.writeHead(200,{"content-type":"text/html; charset=utf-8","content-length":v.length});return response.end(v);}
 if(request.url==="/v1/billing/webhook"&&request.method==="POST"&&d.billing){const raw=await rawBody(request,1_000_000),signature=String(request.headers["x-billing-signature"]??"");return send(response,200,d.billing.ingest(raw,signature));}
 const token=request.headers.authorization?.replace(/^Bearer\s+/i,"")??"",principal=d.authenticate(token);if(!principal)return send(response,401,{error:"unauthorized"});if(d.rateLimiter&&!d.rateLimiter.consume(principal.tenantId))return send(response,429,{error:"rate_limited"});d.metrics?.increment("api_requests_total",{method:request.method??"UNKNOWN"});
 if(request.url==="/metrics"&&request.method==="GET")return send(response,200,{counters:Object.fromEntries(d.metrics?.counters??[])});
 if(request.method==="POST"&&request.url==="/v1/verifications"){if(!scoped(principal,"verify:write"))return send(response,403,{error:"insufficient_scope"});const input=await body(request);if(typeof input.email!=="string"||typeof input.idempotency_key!=="string")return send(response,400,{error:"email and idempotency_key are required"});const purposes=new Set<VerificationRequest["purpose"]>(["signup_validation","crm_hygiene","authorized_bulk","internal_enterprise","cold_outbound"]),purpose=String(input.purpose??"signup_validation")as VerificationRequest["purpose"];if(!purposes.has(purpose))return send(response,400,{error:"unsupported purpose"});const profile=String(input.profile??"balanced")as VerificationRequest["profile"];if(!new Set(["fast","balanced","deep"]).has(profile))return send(response,400,{error:"unsupported profile"});const usage=quota(d,principal,"verification",input.idempotency_key,1);if(!usage.allowed)return send(response,402,{error:"quota_exceeded",usage});const result=await d.orchestrator.verify(createVerificationRequest({tenantId:principal.tenantId,purpose,originalAddress:input.email,profile,idempotencyKey:input.idempotency_key},d.clock));return send(response,result.state==="pending_refinement"?202:200,result);}
 if(request.method==="POST"&&request.url==="/v1/bulk-verifications"){if(!scoped(principal,"bulk:write"))return send(response,403,{error:"insufficient_scope"});const input=await body(request);if(!Array.isArray(input.emails)||input.emails.length<1||input.emails.length>100||typeof input.idempotency_key!=="string"||input.emails.some(v=>typeof v!=="string"))return send(response,400,{error:"emails (1..100 strings) and idempotency_key are required"});const emails=[...new Set(input.emails as string[])],usage=quota(d,principal,"sync_bulk",input.idempotency_key,emails.length);if(!usage.allowed)return send(response,402,{error:"quota_exceeded",usage});const results=[];for(let i=0;i<emails.length;i++)results.push(await d.orchestrator.verify(createVerificationRequest({tenantId:principal.tenantId,purpose:"authorized_bulk",originalAddress:emails[i]as string,profile:"balanced",idempotencyKey:`${input.idempotency_key}:${i}`},d.clock)));return send(response,results.some(v=>v.state==="pending_refinement")?202:200,{results});}
 if(request.method==="POST"&&request.url==="/v1/bulk-jobs"&&d.bulk){if(!scoped(principal,"bulk:write"))return send(response,403,{error:"insufficient_scope"});const type=String(request.headers["content-type"]??"");let emails:string[],profile:VerificationRequest["profile"]="balanced",webhookUrl:string|undefined;if(type.includes("text/csv"))emails=parseEmailCsv((await rawBody(request)).toString("utf8"));else{const input=await body(request);if(!Array.isArray(input.emails)||input.emails.some(v=>typeof v!=="string"))return send(response,400,{error:"emails must be an array of strings"});emails=input.emails as string[];profile=String(input.profile??"balanced")as VerificationRequest["profile"];if(!new Set(["fast","balanced","deep"]).has(profile))return send(response,400,{error:"unsupported profile"});webhookUrl=typeof input.webhook_url==="string"?input.webhook_url:undefined;}const reference=String(request.headers["idempotency-key"]??createHash("sha256").update(emails.join("\n")).digest("hex")),usage=quota(d,principal,"bulk_job",reference,new Set(emails).size);if(!usage.allowed)return send(response,402,{error:"quota_exceeded",usage});return send(response,202,await d.bulk.create(principal.tenantId,emails,profile,webhookUrl));}
 const bulk=/^\/v1\/bulk-jobs\/([^/]+)(\/export)?$/.exec(request.url??"");if(request.method==="GET"&&bulk&&d.bulkRepository){if(!scoped(principal,"bulk:read"))return send(response,403,{error:"insufficient_scope"});const job=await d.bulkRepository.get(bulk[1]as string,principal.tenantId);if(!job)return send(response,404,{error:"not_found"});const items=await d.bulkRepository.listItems(job.id,principal.tenantId);if(bulk[2]){const csv=exportResultsCsv(items);response.writeHead(200,{"content-type":"text/csv","content-disposition":`attachment; filename="${job.id}.csv"`});return response.end(csv);}return send(response,200,{...job,progress:job.total?(job.completed+job.failed)/job.total:0,items});}
 const verification=/^\/v1\/verifications\/([^/]+)$/.exec(request.url??"");if(request.method==="GET"&&verification){if(!scoped(principal,"verify:read"))return send(response,403,{error:"insufficient_scope"});const requestRecord=await d.repository.get(verification[1]as string);if(!requestRecord||requestRecord.tenantId!==principal.tenantId)return send(response,404,{error:"not_found"});const result=await d.repository.getResult(verification[1]as string);return result?send(response,result.state==="pending_refinement"?202:200,result):send(response,404,{error:"not_found"});}
 if(d.product&&"monthlyQuota"in principal){if(request.method==="GET"&&request.url==="/v1/account"){if(!scoped(principal,"account:read"))return send(response,403,{error:"insufficient_scope"});return send(response,200,{tenant_id:principal.tenantId,plan:principal.plan,status:principal.status,usage:d.product.usage(principal.tenantId)});}if(request.method==="GET"&&request.url==="/v1/account/api-keys"){if(!scoped(principal,"account:read"))return send(response,403,{error:"insufficient_scope"});return send(response,200,{keys:d.product.listKeys(principal.tenantId)});}if(request.method==="POST"&&request.url==="/v1/account/api-keys"){if(!scoped(principal,"keys:write"))return send(response,403,{error:"insufficient_scope"});const input=await body(request),allowed=new Set<Scope>(["verify:read","verify:write","bulk:read","bulk:write","account:read"]);if(typeof input.name!=="string"||!Array.isArray(input.scopes)||input.scopes.some(v=>typeof v!=="string"||!allowed.has(v as Scope)))return send(response,400,{error:"valid name and scopes are required"});return send(response,201,d.product.createKey(principal.tenantId,input.name,input.scopes as Scope[]));}const revoke=/^\/v1\/account\/api-keys\/([^/]+)$/.exec(request.url??"");if(request.method==="DELETE"&&revoke){if(!scoped(principal,"keys:write"))return send(response,403,{error:"insufficient_scope"});return d.product.revokeKey(principal.tenantId,revoke[1]as string,principal.keyId)?send(response,200,{revoked:true}):send(response,404,{error:"not_found"});}if(request.method==="GET"&&request.url==="/v1/account/audit"){if(!scoped(principal,"account:read"))return send(response,403,{error:"insufficient_scope"});return send(response,200,{events:d.product.listAudit(principal.tenantId)});}}
 return send(response,404,{error:"not_found"});
 }catch(error){const status=typeof error==="object"&&error&&"status"in error?Number((error as{status:unknown}).status):500;return send(response,status,{error:status===500?"internal_error":(error as Error).message});}});
