import { DatabaseSync } from "node:sqlite";
import type { VerificationResult } from "../domain/model.ts";
import type { BulkItem, BulkJob, BulkRepository } from "./model.ts";
export class SqliteBulkRepository implements BulkRepository {
  private readonly db:DatabaseSync;
  constructor(path:string){this.db=new DatabaseSync(path);this.db.exec("PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;");}
  async create(job:BulkJob,emails:readonly string[]):Promise<BulkJob>{this.db.exec("BEGIN IMMEDIATE");try{this.db.prepare("INSERT INTO bulk_jobs(id,tenant_id,state,profile,total,completed,failed,webhook_url,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)").run(job.id,job.tenantId,job.state,job.profile,job.total,0,0,job.webhookUrl??null,job.createdAt,job.updatedAt);const insert=this.db.prepare("INSERT INTO bulk_items(job_id,ordinal,email,state,attempts,available_at) VALUES(?,?,?,'queued',0,?)");emails.forEach((email,i)=>insert.run(job.id,i,email,job.createdAt));this.db.exec("COMMIT");return job;}catch(error){this.db.exec("ROLLBACK");throw error;}}
  async get(id:string,tenantId:string):Promise<BulkJob|undefined>{const r=this.db.prepare("SELECT * FROM bulk_jobs WHERE id=? AND tenant_id=?").get(id,tenantId) as Record<string,unknown>|undefined;return r&&toJob(r);}
  async listItems(id:string,tenantId:string):Promise<readonly BulkItem[]>{return(this.db.prepare("SELECT i.* FROM bulk_items i JOIN bulk_jobs j ON j.id=i.job_id WHERE i.job_id=? AND j.tenant_id=? ORDER BY ordinal").all(id,tenantId)as Record<string,unknown>[]).map(toItem);}
  async claim(limit:number,now:string):Promise<readonly BulkItem[]>{this.db.exec("BEGIN IMMEDIATE");try{const rows=this.db.prepare("SELECT i.*,j.tenant_id FROM bulk_items i JOIN bulk_jobs j ON j.id=i.job_id WHERE i.state='queued' AND i.available_at<=? ORDER BY i.available_at,i.job_id,i.ordinal LIMIT ?").all(now,limit)as Record<string,unknown>[];const update=this.db.prepare("UPDATE bulk_items SET state='running',attempts=attempts+1 WHERE job_id=? AND ordinal=? AND state='queued'");const claimed:BulkItem[]=[];for(const row of rows)if(update.run(row.job_id,row.ordinal).changes)claimed.push(toItem({...row,state:"running",attempts:Number(row.attempts)+1}));this.db.exec("COMMIT");return claimed;}catch(error){this.db.exec("ROLLBACK");throw error;}}
  async complete(item:BulkItem,result:VerificationResult):Promise<void>{this.db.prepare("UPDATE bulk_items SET state='complete',verification_id=?,result_json=?,error=NULL WHERE job_id=? AND ordinal=?").run(result.verificationId,JSON.stringify(result),item.jobId,item.ordinal);}
  async fail(item:BulkItem,error:string,retryAt?:string):Promise<void>{this.db.prepare("UPDATE bulk_items SET state=?,error=?,available_at=? WHERE job_id=? AND ordinal=?").run(retryAt?"queued":"failed",error,retryAt??item.availableAt,item.jobId,item.ordinal);}
  async finalize(jobId:string):Promise<BulkJob>{const c=this.db.prepare("SELECT SUM(state='complete') completed,SUM(state='failed') failed,SUM(state IN ('queued','running')) pending FROM bulk_items WHERE job_id=?").get(jobId)as Record<string,unknown>;const state=Number(c.pending)>0?"running":Number(c.failed)>0?"partial_failure":"complete";const now=new Date().toISOString();this.db.prepare("UPDATE bulk_jobs SET state=?,completed=?,failed=?,updated_at=? WHERE id=?").run(state,Number(c.completed),Number(c.failed),now,jobId);return toJob(this.db.prepare("SELECT * FROM bulk_jobs WHERE id=?").get(jobId)as Record<string,unknown>);}
  close():void{this.db.close();}
}
const toJob=(r:Record<string,unknown>):BulkJob=>({id:String(r.id),tenantId:String(r.tenant_id),state:String(r.state)as BulkJob["state"],profile:String(r.profile)as BulkJob["profile"],total:Number(r.total),completed:Number(r.completed),failed:Number(r.failed),webhookUrl:r.webhook_url?String(r.webhook_url):undefined,createdAt:String(r.created_at),updatedAt:String(r.updated_at)});
const toItem=(r:Record<string,unknown>):BulkItem=>({tenantId:r.tenant_id?String(r.tenant_id):undefined,jobId:String(r.job_id),ordinal:Number(r.ordinal),email:String(r.email),state:String(r.state)as BulkItem["state"],verificationId:r.verification_id?String(r.verification_id):undefined,result:r.result_json?JSON.parse(String(r.result_json)):undefined,error:r.error?String(r.error):undefined,attempts:Number(r.attempts),availableAt:String(r.available_at)});
