import{createHash,randomBytes,timingSafeEqual}from"node:crypto";import{DatabaseSync}from"node:sqlite";import{newId}from"../domain/ids.ts";
export type Scope="verify:read"|"verify:write"|"bulk:read"|"bulk:write"|"account:read"|"keys:write";
export interface Principal{tenantId:string;keyId:string;scopes:ReadonlySet<Scope>;plan:string;status:"beta"|"active"|"suspended";monthlyQuota:number;}
export class ProductStore{private readonly db:DatabaseSync;constructor(path:string){this.db=new DatabaseSync(path);this.db.exec("PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;");}
 ensureTenant(input:{id:string;name:string;plan?:string;monthlyQuota?:number}):void{const now=new Date().toISOString();this.db.prepare("INSERT INTO tenants(id,name,status,plan,monthly_quota,created_at,updated_at) VALUES(?,?,'beta',?,?,?,?) ON CONFLICT(id) DO NOTHING").run(input.id,input.name,input.plan??"beta",input.monthlyQuota??10000,now,now);}
 createKey(tenantId:string,name:string,scopes:readonly Scope[]):{id:string;key:string;prefix:string}{const id=newId("key"),key=`vfy_${randomBytes(24).toString("base64url")}`,prefix=key.slice(0,12),now=new Date().toISOString();this.db.prepare("INSERT INTO api_keys(id,tenant_id,name,key_prefix,key_digest,scopes_json,created_at) VALUES(?,?,?,?,?,?,?)").run(id,tenantId,name,prefix,digest(key),JSON.stringify(scopes),now);this.audit(tenantId,id,"api_key.created","api_key",id,{name,scopes});return{id,key,prefix};}
 importKey(tenantId:string,name:string,key:string,scopes:readonly Scope[]):void{const existing=this.db.prepare("SELECT id FROM api_keys WHERE key_digest=?").get(digest(key));if(existing)return;const id=newId("key"),now=new Date().toISOString();this.db.prepare("INSERT INTO api_keys(id,tenant_id,name,key_prefix,key_digest,scopes_json,created_at) VALUES(?,?,?,?,?,?,?)").run(id,tenantId,name,key.slice(0,12),digest(key),JSON.stringify(scopes),now);}
 authenticate(key:string):Principal|undefined{if(!key||key.length<20)return;const candidate=Buffer.from(digest(key),"hex");const row=this.db.prepare("SELECT k.id key_id,k.key_digest,k.scopes_json,t.* FROM api_keys k JOIN tenants t ON t.id=k.tenant_id WHERE k.key_digest=? AND k.revoked_at IS NULL").get(candidate.toString("hex"))as Record<string,unknown>|undefined;if(!row||!timingSafeEqual(candidate,Buffer.from(String(row.key_digest),"hex"))||row.status==="suspended")return;this.db.prepare("UPDATE api_keys SET last_used_at=? WHERE id=?").run(new Date().toISOString(),row.key_id);return{tenantId:String(row.id),keyId:String(row.key_id),scopes:new Set(JSON.parse(String(row.scopes_json))as Scope[]),plan:String(row.plan),status:String(row.status)as Principal["status"],monthlyQuota:Number(row.monthly_quota)};}
 consume(principal:Principal,kind:string,referenceId:string,quantity:number):{allowed:boolean;used:number;limit:number}{const start=new Date();start.setUTCDate(1);start.setUTCHours(0,0,0,0);this.db.exec("BEGIN IMMEDIATE");try{const used=Number((this.db.prepare("SELECT COALESCE(SUM(quantity),0) used FROM usage_ledger WHERE tenant_id=? AND occurred_at>=?").get(principal.tenantId,start.toISOString())as{used:number}).used);if(quantity<1||used+quantity>principal.monthlyQuota){this.db.exec("ROLLBACK");return{allowed:false,used,limit:principal.monthlyQuota};}this.db.prepare("INSERT OR IGNORE INTO usage_ledger(id,tenant_id,quantity,kind,reference_id,occurred_at) VALUES(?,?,?,?,?,?)").run(newId("use"),principal.tenantId,quantity,kind,referenceId,new Date().toISOString());this.db.exec("COMMIT");return{allowed:true,used:used+quantity,limit:principal.monthlyQuota};}catch(error){this.db.exec("ROLLBACK");throw error;}}
 usage(tenantId:string):{used:number;limit:number}{const start=new Date();start.setUTCDate(1);start.setUTCHours(0,0,0,0);const row=this.db.prepare("SELECT t.monthly_quota quota_limit,COALESCE(SUM(u.quantity),0) used FROM tenants t LEFT JOIN usage_ledger u ON u.tenant_id=t.id AND u.occurred_at>=? WHERE t.id=? GROUP BY t.id").get(start.toISOString(),tenantId)as{used:number;quota_limit:number};return{used:Number(row.used),limit:Number(row.quota_limit)};}
 listKeys(tenantId:string):unknown[]{return this.db.prepare("SELECT id,name,key_prefix,scopes_json,created_at,last_used_at,revoked_at FROM api_keys WHERE tenant_id=? ORDER BY created_at").all(tenantId).map((r:any)=>({...r,scopes:JSON.parse(r.scopes_json),scopes_json:undefined}));}
 revokeKey(tenantId:string,id:string,actor:string):boolean{const result=this.db.prepare("UPDATE api_keys SET revoked_at=? WHERE id=? AND tenant_id=? AND revoked_at IS NULL").run(new Date().toISOString(),id,tenantId);if(result.changes)this.audit(tenantId,actor,"api_key.revoked","api_key",id,{});return!!result.changes;}
 audit(tenantId:string,actor:string,action:string,targetType:string,targetId:string|undefined,metadata:Record<string,unknown>):void{this.db.prepare("INSERT INTO audit_events(id,tenant_id,actor_id,action,target_type,target_id,metadata_json,occurred_at) VALUES(?,?,?,?,?,?,?,?)").run(newId("aud"),tenantId,actor,action,targetType,targetId??null,JSON.stringify(metadata),new Date().toISOString());}
 listAudit(tenantId:string,limit=100):unknown[]{return this.db.prepare("SELECT id,actor_id,action,target_type,target_id,metadata_json,occurred_at FROM audit_events WHERE tenant_id=? ORDER BY occurred_at DESC LIMIT ?").all(tenantId,Math.min(limit,500)).map((r:any)=>({...r,metadata:JSON.parse(r.metadata_json),metadata_json:undefined}));}
 applyEntitlement(input:{provider:string;externalId:string;eventType:string;tenantId:string;plan:string;monthlyQuota:number;payloadDigest:string}):boolean{this.db.exec("BEGIN IMMEDIATE");try{const inserted=this.db.prepare("INSERT OR IGNORE INTO billing_events(provider,external_id,event_type,payload_digest,received_at) VALUES(?,?,?,?,?)").run(input.provider,input.externalId,input.eventType,input.payloadDigest,new Date().toISOString());if(!inserted.changes){this.db.exec("ROLLBACK");return false;}const now=new Date().toISOString();this.db.prepare("UPDATE tenants SET plan=?,monthly_quota=?,updated_at=? WHERE id=?").run(input.plan,input.monthlyQuota,now,input.tenantId);this.db.prepare("UPDATE billing_events SET processed_at=? WHERE provider=? AND external_id=?").run(now,input.provider,input.externalId);this.db.exec("COMMIT");this.audit(input.tenantId,"billing","entitlement.updated","tenant",input.tenantId,{plan:input.plan,monthlyQuota:input.monthlyQuota});return true;}catch(error){this.db.exec("ROLLBACK");throw error;}}
 close():void{this.db.close();}}
const digest=(value:string)=>createHash("sha256").update(value).digest("hex");
